version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - websrc:/var/www/html/:z
    depends_on:
      - php

  php:
    build:
      context: docker/php
    volumes:
      - websrc:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/extra-php.ini
    user: $UID
    working_dir: /var/www/html
    environment:
      - DATABASE_URL=mysql://myuser:myuser1@db:3306/mydb?serverVersion=5.7
    depends_on:
      - composer

  docdbmigration:
    build:
      context: docker/php
    command: sh -c "bin/wait-for-it.sh db:3306 && bin/console doctrine:migrations:migrate --no-interaction"
    user: $UID
    depends_on:
      - composer
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - websrc:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/extra-php.ini
    environment:
      - DATABASE_URL=mysql://myuser:myuser1@db:3306/mydb?serverVersion=5.7

  composer:
    build:
      context: docker/composer
    user: $UID
    volumes:
      - websrc:/app
    command: composer install
    working_dir: /app
    environment:
      - COMPOSER_HOME=/home/composer
      - HOME=/home/composer
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
#    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: myuser
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser1
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf

volumes:
  mysqldata:
  websrc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./

